### ISSUE TITLE
Running Information is not accessible on the Java API

### ISSUE THREAD

**Issue by hurtadosanti** [operator-framework/java-operator-sdk#1905]
For the operator will be nice to have metrics and information inside the java code to create custom metrics. For instance, how many custom resources a reconciler or the complete operator manages. 

The scenario could be extended depending on the status. For instance, if there are CR's that are on a failing or error status, even though this is a bit business specific.

When an operator is running, a probable scenario is to handle more than one Custom Resource of the same type, which becomes an intriguing metric to know on a multinamespace setting of a large cluster. 

i.e. for the web page example, https://github.com/java-operator-sdk/java-operator-sdk/blob/main/sample-operators/webpage/src/main/java/io/javaoperatorsdk/operator/sample/customresource/WebPage.java there could be many webpages on different namespaces, and how many of them are running correctly(have all the dependencies complete).

**Comment by metacosm** [comment]
I *think* it should be possible to determine the information you want using the default metrics implementation by querying / filtering the produced metrics in your metrics aggregator of choice, no?

**Comment by hurtadosanti** [comment]
Thanks @csviri the fact remains that there is no API access from Java to this information, the metrics is a good example but not the only use case.

**Comment by csviri** [comment]
@hurtadosanti  what are other use cases?
