### ISSUE TITLE
Rename `name` of Dependent Resource to `id` in definition section 

### ISSUE THREAD

**Issue by csviri** [operator-framework/java-operator-sdk#1921]
It can be confusing (it is for some), that in dependent resource has a name when defining for example multiple DR that depends on each other. But also most of KubernetesResources has a `name`. So this can be misinterpreted, in a way that we are setting the name of the dependent resource this way. So would rather rename it to `id`.

from:

```java
@ControllerConfiguration( 
    dependents = {@Dependent(name="MyDependentName", type = ConfigMapDependent.class)})
```

to:

```java
@ControllerConfiguration(
   dependents = {@Dependent(id="MyDependentName", type = ConfigMapDependent.class)})
```

**Comment by csviri** [comment]
Coming back to this, it does not feel necessary. Unless you think otherwise @metacosm , I will close this.

**Comment by metacosm** [comment]
I agree, we should clean things that could obviously be better but I don't think we should be changing / renaming things just for the sake of it. In this instance, I don't think that renaming the `name` attribute will make things clearer so I'd rather we keep it, indeed.
