### ISSUE TITLE
Change Naming of `reconcilePrecondition` for v5

### ISSUE THREAD

**Issue by csviri** [operator-framework/java-operator-sdk#1926]
It can be confusing that in the precondition there is `reconcile` included, this not really describes the deletion that happens if this condition does not hold.
Maybe it should be just `condition` ?

**Comment by metacosm** [comment]
@Javatar81 the idea is that the condition is a barrier for the secondary reconciliation meaning that if the condition is not `true` then the secondary shouldn't exist and therefore not reconciled (because, if it existed, it certainly should be reconciled to decide whether or not its state is conform to the desired state described by the primary resource). I do agree, though, that this is somewhat confusing.

**Comment by csviri** [comment]
Let's assume this scenario:

https://github.com/operator-framework/java-operator-sdk/blob/af7706452752dadcecaccf549640066c795311d3/sample-operators/webpage/src/main/java/io/javaoperatorsdk/operator/sample/WebPageManagedDependentsReconciler.java#L22-L22

We want in the CR a flag to create an Ingress or not. If we want to describe such cases, we need a conditional resource, since some might want to change this flag from true to false. Thus remove the Ingress. 

Side note: not reconciling a resource does not make sense, only case when it happens or might happen if a resource B depends on resource  A, where A has a ready post condition; and before it already happened that A was ready and B reconciled, but now A is not ready (like new version deployment happening or such), and B is not reconciled until the A is ready.
Otherwise workflow reconciles in a run all the resources.

**Comment by csviri** [comment]
The activation condition is very limited atm, for example you cannot make resources properly of same type with activation condition. (Will describe more the limitations in the docs). If you know that the resources will be always present on the cluster you can replace the activationCondition with reconcilePreCondition. Vice versa is not working always, just in some limited use cases.

Technically the differences is how the event source is registered, when a resource has an activation condition, the event source is not registered while the condition is not true. This is much more trickier than it might sound. 

If the limitations would be solved the activation condition functionally replace in theory the reconcile condition, but registering dynamically the event sources is less efficient (although the differences might not be noticable).

We will explore more the possibilities of the activation condition. TBH it would be much easier to support it with just the standalone dependent resources.

**Comment by csviri** [comment]
see discussion in the PR, we will stick with the original naming for now.
