### ISSUE TITLE
Configurable LeaderCallbacks

### ISSUE THREAD

**Issue by r57** [operator-framework/java-operator-sdk#2009]
When setting up the leader election it would be great to be able to provide own `LeaderCallbacks`.

**Use case**
I'm required to integrate with health monitoring system and send regular hearth beats upstream with interval dictated by the system to the endpoint dictated by the system. So in HA setup I'm thinking only leader should manage this and persist the information in some object so any new elected leader can just carry on. But currently there's no way to tell if the running instance is actually leading or not.

**Comment by csviri** [comment]
Makes sense to, can add this into next minor release.

**Comment by csviri** [comment]
@r57 added a PR, please take a look, if this is something that you thought of
