### ISSUE TITLE
ConfigurationServiceProvider migration

### ISSUE THREAD

**Issue by andreaTP** [operator-framework/java-operator-sdk#2020]
## Bug Report

Seems like `ConfigurationServiceProvider` have been removed as part of [this PR](https://github.com/operator-framework/java-operator-sdk/pull/1865/files), but there are a few left-overs:

- there are still references to the class in the docs: https://github.com/search?q=repo%3Aoperator-framework%2Fjava-operator-sdk%20ConfigurationServiceProvider&type=code
- I'm unable to find a "migration guide"

**Comment by csviri** [comment]
Good catch, it was mostly an internal stuff, will fix the docs.

**Comment by csviri** [comment]
> I'm looking for a way to replace those lines: https://github.com/Apicurio/apicurio-registry/blob/e4f48bae6ab0e434e8e4b59525632b0afd888e4a/operator/controller/src/test/java/io/apicurio/registry/operator/it/ITBase.java#L170-L172
> 
> which are similar to the test infrastructure of Keycloak, cc. @shawkins

you can just simply use the override param when creating the operator
