### ISSUE TITLE
KubernetesClient creation

### ISSUE THREAD

**Issue by shawkins** [operator-framework/java-operator-sdk#2040]
This is a follow-up to https://github.com/quarkusio/quarkus/issues/35383 

When running the keycloak integration tests we see 4 clients being created.  

- One client is created by the BaseOperatorTest, which is generally the client we expect to use throughout
- One is created by OperatorProducer, which is a little unexpected because there is no explicit usage of the operator through quarkus / cdi
- One is being creaed by OpenshiftClientProducer - this seems to be because a couple of places in our code currently inject a client (which I'll try to remove)
- One is being addressed by https://github.com/fabric8io/kubernetes-client/issues/5315

Is the creation of a separate client by the OperatorProducer expected, or is this just another issue introduced by Keycloak's manual construction of the Operator?

cc @manusa

**Comment by csviri** [comment]
If I understand correctly this is related only to Quarkus Extension, should we move the issue there?

**Comment by metacosm** [comment]
Looks like it, yes, unfortunately, we can't move the issues easily since the projects are not part of the same org :(
Created https://github.com/quarkiverse/quarkus-operator-sdk/issues/702 instead.
