### ISSUE TITLE
Is it possible to deploy a clean up job after dependent resources are deleted?

### ISSUE THREAD

**Issue by raminqaf** [operator-framework/java-operator-sdk#2057]
Hello,
I am writing an Operator that the primary resource manages deployment, service, configMap, etc. The resource that I am creating needs a graceful shutdown. This can be achieved through a `Job` (i.e., clean-up job) resource and after all the secondary resources (deployment, service, configMap, etc.) are deleted. What should I do in my `cleanup` method to achieve this?

Can this be achieved by calling the `noFinalizerRemoval()` and then processing with the deployment of the clean-up job and then calling `defaultDelete()`?

```java
    @Override
    public DeleteControl cleanup(final MyComplexApp resource, final Context<MyComplexApp> context) {
        DeleteControl.noFinalizerRemoval();
        
        // Deploy clean-up job (and wait to finish?) ...
        
       return DeleteControl.defaultDelete();
    }
```

**Comment by metacosm** [comment]
I guess it depends if you care about the result of the `Job`. Also, are you using the dependent resource feature?

**Comment by raminqaf** [comment]
@metacosm Yeah, I am using the dependent resource feature:
```java
@ControllerConfiguration(
        dependents = {
                @Dependent(type = DeploymentDependentResource.class),
                //...
        })
public class MyComplexAppReconciler implements Reconciler< MyComplexApp >, ErrorStatusHandler< MyComplexApp >,
        Cleaner< MyComplexApp > {
        // ...
}
```
However, I am unsure if the `Job` should be defined as a dependent resource. For this example, the cleanup job responsibility is to delete a table in the database.

**Comment by csviri** [comment]
> However, I am unsure if the Job should be defined as a dependent resource. For this example, the cleanup job responsibility is to delete a table in the database.

Porbably not, 
what you mention here should be the way to go:

> Can this be achieved by calling the noFinalizerRemoval() and then processing with the deployment of the clean-up job and then calling defaultDelete()?

**Comment by raminqaf** [comment]
@csviri I'll give it a shot and write an update, on how it went! Thanks!

**Comment by raminqaf** [comment]
@metacosm & @csviri I have updated the cleanup method, and now it looks like this. For simplicity, I am loading the cleanup job Yaml file staticly. 
```java
    @Override
    public DeleteControl cleanup(final ComplexApp complexApp, final Context<ComplexApp> context) {
        final DeleteControl deleteControl = DeleteControl.noFinalizerRemoval();

        final Job job = loadYaml(Job.class, Utils.class, "cleanup-job.yaml");
        final KubernetesClient client = context.getClient();
        final String namespace = complexApp.getMetadata().getNamespace();

        final Job jobInCluster = client.resource(job).inNamespace(namespace).get();

        if (jobInCluster == null) {
            client.resource(job)
                    .inNamespace(namespace)
                    .create();
            client.resource(job)
                    .waitUntilReady(10, TimeUnit.SECONDS);
        } else {
            if(jobInCluster.getStatus() != null && jobInCluster.getStatus().getSucceeded() == 1) {
                // Maybe even more checks and conditions to be checked here...
                return DeleteControl.defaultDelete();
            }
        }
        return deleteControl.rescheduleAfter(10, TimeUnit.SECONDS);
   }
```
I hoped the cleanup function would be called again after the rescheduled is returned. Am I missing something here?

**Comment by csviri** [comment]
> I hoped the cleanup function would be called again after the rescheduled is returned. Am I missing something here? 

No, that should be the case.

This is the integration test for it: https://github.com/java-operator-sdk/java-operator-sdk/blob/32586bc277301e4b08b8d04ed6e34e34b9291596/operator-framework/src/test/java/io/javaoperatorsdk/operator/CleanerForReconcilerIT.java#L46-L46

**Comment by raminqaf** [comment]
@csviri Thanks for the link! It helped me to understand the cleanup better. I want to delete all the dependent resources. After a successful deletion of the DRs, I want then check with a client API that a condition is set to deploy the clean-up job. And lastly, delete the Primary Resouce. Do you think this is also achievable?

```java
    @Override
    public DeleteControl cleanup(final ComplexApp complexApp, final Context<ComplexApp> context) {
        // 1. Delete all the DRs
        
        // 2. If all the DRs are cleared
        
        // 3. Check with a client API if some conditions are set. If not reschedule.
        
        // 4. Deploy Clean up Job
        
        // 5. Call DeleteControl.defaultDelete();
   }
```

**Comment by csviri** [comment]
Absolutely, if you use managed DRs, (1) this should be done for you. Check also the current state of DRs either from context of simple the cache.

**Comment by raminqaf** [comment]
@csviri Thanks! Could you please point me to some sample code or documentation regarding the state of the DRs?

**Comment by csviri** [comment]
@raminqaf  You can check either just the current state from `context`.  But though the `context` you can access this: https://github.com/java-operator-sdk/java-operator-sdk/blob/a6a57afd0079f4b64fed42292ef1298e3d7d5187/operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/reconciler/dependent/managed/ManagedDependentResourceContext.java#L55-L55
