### ISSUE TITLE
When operator restart it trying to Reconciler again

### ISSUE THREAD

**Issue by chethankumar4046** [operator-framework/java-operator-sdk#2070]
#### What did you do?

restarting operator pod

#### What did you expect to see?

should not Reconciler again

trying to Reconciler again

#### Environment

**Kubernetes cluster type:**

vanilla

`$ Mention java-operator-sdk version from pom.xml file`

4.0.3

`$ java -version`

17

**Comment by csviri** [comment]
see recent discussion here: https://github.com/quarkiverse/quarkus-operator-sdk/issues/718

**Comment by shawkins** [comment]
Unless you save the informer states and re-initialize them with the last known state, the operator will need to reconciler on restart.

**Comment by csviri** [comment]
Yes, but then there are generic EventSources, which again would be need to implement such logic. Not sure if this is feasible. Did you see implemented on some controller? @shawkins

**Comment by shawkins** [comment]
> Did you see implemented on some controller?

It was the impetis for the upstream intial state feature.  The user was maintaining a persistant store of the state that was fully reconciled via their ResourceEventHandler, then using that as the initial state on a restart.  So applicable to informer based sources if you also track what has been reconciled, but not applicalbe in general.

**Comment by chethankumar4046** [comment]
> Unless you save the informer states and re-initialize them with the last known state, the operator will need to reconciler on restart.
> 
> And It's not as simple as that - you have to save the informer state of only what has been fully reconciled - if anything is pending, then you may skip that on restart.

@shawkins Thanks for your replay, 
Can i have some sample or resource for how to implement

**Comment by metacosm** [comment]
I would say that this isn't something that is widely used and actually goes against the kubernetes philosophy: controllers are supposed to be stateless and reconstruct the desired state from the observable state of the cluster. There might be cases where initial reconciliation might be expensive but I think that's outside the scope of this SDK, at least not until there is a significant demand for it.

**Comment by shawkins** [comment]
> Can i have some sample or resource for how to implement

I'm not aware of any full blown example, in particular one that would be based upon the operator sdk - I don't think it's aware of initial state, but it does look like an itemstore can be provided which could do the same thing.

>  There might be cases where initial reconciliation might be expensive but I think that's outside the scope of this SDK, at least not until there is a significant demand for it.

Ideally restarts of your operator should be infrequent and the cost of doing the initial resolving shouldn't be too great.  Are you dealing with a circumstance where you a frequently restarting, dealing with large amounts of state, or the side affect of reconciliation targets a back end, etc.?

**Comment by csviri** [comment]
Will close this if no objections.
