### ISSUE TITLE
Make @GradualRetry inherited

### ISSUE THREAD

**Issue by BramMeerten** [operator-framework/java-operator-sdk#2091]
When a reconciler has the `@GradualRetry` annotation on a superclass, it will not be used:
https://github.com/operator-framework/java-operator-sdk/blob/main/operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/BaseConfigurationService.java#L280
```java
final Class<? extends Annotation> configurationClass = (Class<? extends Annotation>) Utils.getFirstTypeArgumentFromSuperClassOrInterface(instance.getClass(), AnnotationConfigurable.class);
final var configAnnotation = reconciler.getClass().getAnnotation(configurationClass);
```

Solution is to add @Inherited to @GradualRetry

I'd be willing to contribute this change if this is an acceptable enhancement. I did a similar change in the past: https://github.com/operator-framework/java-operator-sdk/issues/1347

**Reason why this is needed in my case**
I'm using micronaut framework. And when I inject my reconciler, I actually inject a proxy class that is a subclass of my Reconciler implementation (because I'm using micronaut AOP)..

**Comment by csviri** [comment]
Sure, feel free to add a PR! thank you!

**Comment by BramMeerten** [comment]
I just went through all the annotations in the framework to see if others might benefit from this too.
The following should be Inherited I think:
- `@GradualRetry`
- `@Configured`
- `@RateLimited`

Will do a PR this weekend
