### ISSUE TITLE
How to create a golang struct for crd generate by java-operator-sdk

### ISSUE THREAD

**Issue by shuaiyy** [operator-framework/java-operator-sdk#2100]
I want to use crd `flinkdeployments.flink.apache.org` in my go project, but the flink-operator is build by  java-operator-sdk, and no go struct client object provided.

How can a generate a golang client-go api object struct ?

**Comment by csviri** [comment]
There is I guess a CRD generated from the java classes in flink. I would expect that go supports CRD -> go Struct , generator, but this might not be the case based on this:
https://github.com/operator-framework/operator-sdk/issues/1208

So based on this you would need to write the structs manually.

**Comment by rmetzger** [comment]
I've actually gotten somewhere by only using the `openAPIV3Schema` field from the CRD and using this:

https://github.com/oapi-codegen/oapi-codegen?tab=readme-ov-file#generating-api-models
