### ISSUE TITLE
Custom Resource as a Standalone Dependent Resource

### ISSUE THREAD

**Issue by penev-ff** [operator-framework/java-operator-sdk#2145]
Hi,

I have a case in which I mange my dependent resources as standalone dependent resources. As of now, I was able to create and manage all the dependent resources that I need (native K8s Fabric8 resources and K8s Fabric8 resources provided by extension - Istio). The issue arises from my desire to manage additional dependent resources (Custom Resources) which are not provided by the K8s Fabric8 client (native K8s resources) or any of its [CR extensions](https://github.com/fabric8io/kubernetes-client/tree/main/extensions).

Can it be done in any way?

**Comment by csviri** [comment]
Hi @penev-ff , 

yes, fabrioc8 client supports generating classes from CRD, and just use those in Dependent Resources, this is the preferred way:

https://github.com/java-operator-sdk/java-operator-sdk/blob/6591e0d47cda51eced485e9c396bafa9b59048e4/sample-operators/leader-election/pom.xml#L87-L87

An other (typeless) approach is on the way, see:
https://github.com/operator-framework/java-operator-sdk/pull/2136

Will be included in the next minor release.
