### ISSUE TITLE
Provide possibilty to update the status of a primary Custom Resource upon deletion

### ISSUE THREAD

**Issue by ivanchuchulski** [operator-framework/java-operator-sdk#2151]
Hello, 

We're writing an Operator and we have the requirement, that upon deletion of a `CustomResource`, a property in its `Status` sub-resource should be modified as it's monitored by other controllers in the cluster. Currently our `Reconciler` is implementing the `Cleaner` interface in we manually take care of deleting our standalone dependent resources in the `cleanup` method. 

However I theres is no method similar to `UpdateControl.patchStatus` in the `DeleteControl` class. We've managed maybe to workaround that, by doing some manual patching of the status via an instance of the Fabric8 client `client.resources(MyApp.class).resource(myApp.setStatus(...)).updateStatus();` (here `myApp` is the `cleanup` method parameter) and returning `DeleteControl.noFinalizerRemoval().rescheduleAfter(5, TimeUnit.SECONDS);` for example.

However, a call to the `cleanup` is immediately observed, not after the 5 seconds reschedule period as specified by the `rescheduleAfter()`. When the aforementioned logic is executed in the second call I can see that the needed value of the property in the `Status` is changed and then as we have a check for that, we proceed with the deletion of the dependent resources and finally return `DeleteControl.defaultDelete();`. I'm not sure if our approach is correct and fault-proof.

Would there be a possibility to implement some kind of an equivalent to the `UpdateControl.patchStatus` in the `DeleteControl` class, or is there some other way of doing an update to the Status when the CR is removed that I've missed? 

Best Regards

**Comment by csviri** [comment]
Hi @ivanchuchulski , the reason this is not covered is that the resource should not be modified after it was deleted (in this case just the deletionTimestamp added), from that point the only operation on the resource should be the finalizer removal. (Well at least this is how I remember it from K8S docs, but tbh I was not able to find where did I read this now). So this is the reason that there is no patch, and the mentioned scenarion not supported / tested. Therefore probably there is such "bug" what is rather an unspecified behavior. 

One question if the other controller also adding a finalizer that watches the status?

Maybe would be good to discuss you scenario in Kubernetes Operator channel here, and see what the community advices in such situation, could you maybe describe you scenario here, and discuss further there:
https://kubernetes.slack.com/archives/CAW0GV7A5

Also could you be more precise, what is in the status, that might be interesting for other controller.

**Comment by csviri** [comment]
@ivanchuchulski added a PR that fixes the reScheduling issue for you use case, I see no harm in this. But would be nice to see you use case more in detail.

**Comment by ivanchuchulski** [comment]
Hi @csviri ,
Thank you for the fast reply! Basically what is required is that the Status of our CR has to have some kind of a `state` property, which is being monitored by another central controller/operator. This ways is is done in order to provide end-users some feedback when the installation is ready to be used, or if it has failed for some reason. Thus we set these states in our `reconcile` and `updateErrorStatus` of our `Reconciler`. But there is also a need for status which should indicate when the installation is being removed/disabled, not completely sure about that since we're not developing this central controller.

**Comment by csviri** [comment]
So I guess the central controller adds additional finalizer to the resource (I guess) otherwise might miss the latest status? 
Thank you for the info, will have the fix in the next patch release after review and merged.

**Comment by ivanchuchulski** [comment]
Could you explain what are you planning to do in the linked PR, because I'm not able to understanding the change? Are you targeting the immediate call back to the `cleanup` method when for example `DeleteControl.noFinalizerRemoval().rescheduleAfter(5, TimeUnit.SECONDS);` is returned, but the CR status was updated before manually with a client or something else?
