### ISSUE TITLE
existing itemstore not preserved by overrider

### ISSUE THREAD

**Issue by shawkins** [operator-framework/java-operator-sdk#2152]
#### What did you do?

When using ControllerConfigurationOverrider on a controller that has an customized itemStore, it is nulled out.

#### What did you expect to see?

The original should be preserved.

**Comment by csviri** [comment]
@shawkins can you elaborate more please, how this happens exactly, you customize the event store with `@ControllerConfiguration` and then using `@ControllerConfigurationOverrider` without setting one, then it is nulled out?
