### ISSUE TITLE
How can I change the name of namespaces created by `LocallyRunOperatorExtension`?

### ISSUE THREAD

**Issue by machenity** [operator-framework/java-operator-sdk#2163]
Hi. I wrote some tests using LocallyRunOperatorExtension, but I encountered the following error:

```
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: 
https://xxxxxx.com/api/v1/namespaces. Message: namespaces "xxxxxxxxxoperatorsecuritye2e-xxxxxxxxxxxxxxxxxxxx" 
already exists. Received status: Status(apiVersion=v1, code=409, details=StatusDetails(causes=[], group=null, kind=namespaces, 
name=xxxxxxxxxoperatorsecuritye2e-xxxxxxxxxxxxxxxxxxxx, retryAfterSeconds=null, uid=null, additionalProperties={}), 
kind=Status, message=namespaces "xxxxxxxxxoperatorsecuritye2e-xxxxxxxxxxxxxxxxxxxx" already exists, 
metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), 
reason=AlreadyExists, status=Failure, additionalProperties={}).
```
(I have obscured some data that reveals personal information).

I suspected it was because the [class name + test method name](https://github.com/operator-framework/java-operator-sdk/blob/0b2ec1b62304e206adef7d97491d15634c24c81f/operator-framework-junit5/src/main/java/io/javaoperatorsdk/operator/junit/AbstractOperatorExtension.java#L147-L153) I use as the namespace name was longer than 63 characters, and the UUID part that ensures uniqueness, was truncated, causing two tests running in parallel to create a namespace with the same name.

Looking at the java-operator-sdk code, it appears that there is no configuration to provide a custom namespace name, or at least modify the prefix.

Maybe I missed that configuration?

Besides, if there really is no such configuration, I'd like to add such a feature to the JOSDK, if you don't mind.

**Comment by csviri** [comment]
Hi @machenity , yes this would definetelly would make sense to improve. 
What I can also think of is to always reserve space for UUID at the end of the name for the namespace. Would that fix you problem? 
We could also make this configurable, if really necessary, but that seems to fix the problem nicely and generically. WDYT?

**Comment by csviri** [comment]
@machenity if you would volunteer to do this would be nice :)

**Comment by machenity** [comment]
Thanks for your answer :)

Actually first idea was adding an option accepts custom prefix string or string supplier for namespace.

It would be like this:
```java
LocallyRunOperatorExtension.builder()
	.oneNamespacePerClass(false)
	.namespaceNamePrefix("NAMESPACE_NAME_PREFIX") // pass static string for prefix
	.withNamespaceNameSupplier(() -> "TEST" + new Random().nextInt().toString()) // pass Supplier<String> to call each time a namespace name is created
	.build()
```

But while reading your comments, your idea that truncating name earlier before postfix UUID seems nice. 
Restrictive but quite simpler.

To be honest, I think having a 36-character UUID string in the name is overmuch for a 63-character limit. 🤔 

Just wanna hear your opinion.

**Comment by csviri** [comment]
> To be honest, I think having a 36-character UUID string in the name is overmuch for a 63-character limit.

Yes, definetelly, this can be a very short sequence of random chars.


I can also imagine something like this (very similar to your sample):

```
LocallyRunOperatorExtension.builder()
   .withNamespaceNameSupplier(ExtensionContext context -> context.getTestMethod() + "-"+randomString() )

```
The point is that extension context is passed to access information about the test case (method name). Maybe method name would be just enough in this case, but for sake of generality, this might be a way to go

**Comment by csviri** [comment]
So would be nice to do both, like able to specify namespace name supplier, but also fix this issue with to long names. (The late I would give priority, or in other words a better default supplier)
