### ISSUE TITLE
can i edit `namespaceDeleteTimeout` ??

### ISSUE THREAD

**Issue by 10000-ki** [operator-framework/java-operator-sdk#2169]
after local operator test, deleting ns

> org.awaitility.core.ConditionTimeoutException: Condition with alias 'namespace deleted' didn't complete within 1 minutes  30 seconds because condition with io.javaoperatorsdk.operator.junit.AbstractOperatorExtension was not fulfilled.

I encountered this error

If the `CR` is very heavy
It takes a long time to delete relevant Dependency Resources
So I hope the user can modify the setting value of `namespaceDeleteTimeout`

**Comment by csviri** [comment]
@10000-ki there is already a setting for that, have you tried:

```
     @RegisterExtension
      LocallyRunOperatorExtension.builder()
          .withNamespaceDeleteTimeout(...)
          .withReconciler(new MyReconciler())
          .build();
```

**Comment by 10000-ki** [comment]
oh thank you :)
it works well 👍
