### ISSUE TITLE
Should it be possible to register several reconcilers for the same CR?

### ISSUE THREAD

**Issue by 10000-ki** [operator-framework/java-operator-sdk#2172]
related issue : https://github.com/operator-framework/java-operator-sdk/issues/1171

I know it doesn't fit the josdk idea, But I'd like to ask you again for your opinion.

```kotlin
@ControllerConfiguration(
    labelSelector = "app.kubernetes.io/managed-by=$OPERATOR_LABEL_V1",
    dependents = [
        Dependent(
            type = OpenSearchConfigMap::class,
            name = "OpenSearchConfigMap",
            useEventSourceWithName = CONFIGMAP_EVENT_SOURCE,
        ),
        Dependent(
            type = OpenSearchService::class,
            name = "OpenSearchService",
            useEventSourceWithName = SERVICE_EVENT_SOURCE,
        ),
        Dependent(
            type = OpenSearchDiscoveryService::class,
            name = "OpenSearchDiscoveryService",
            useEventSourceWithName = SERVICE_EVENT_SOURCE,
        ),
        Dependent(
            type = OpenSearchNodeStatefulSet::class,
            name = "OpenSearchNodeStatefulSet",
            useEventSourceWithName = STS_EVENT_SOURCE,
            dependsOn = arrayOf("OpenSearchConfigMap"),
        ),
        Dependent(
            type = OpenSearchNodeDeployment::class,
            name = "OpenSearchNodeDeployment",
            useEventSourceWithName = DEPLOYMENT_EVENT_SOURCE,
            dependsOn = arrayOf("OpenSearchConfigMap"),
        ),
        Dependent(
            type = OpenSearchDashboardsConfigMap::class,
            name = "OpenSearchDashboardsConfigMap",
            useEventSourceWithName = CONFIGMAP_EVENT_SOURCE,
            dependsOn = arrayOf("OpenSearchNodeDeployment"),
        ),
        Dependent(
            type = OpenSearchDashboardsService::class,
            name = "OpenSearchDashboardsService",
            useEventSourceWithName = SERVICE_EVENT_SOURCE,
            dependsOn = arrayOf("OpenSearchNodeDeployment"),
        ),
        Dependent(
            type = OpenSearchDashboardsDeployment::class,
            name = "OpenSearchDashboardsDeployment",
            useEventSourceWithName = DEPLOYMENT_EVENT_SOURCE,
            dependsOn = arrayOf("OpenSearchNodeDeployment"),
        ),
        Dependent(
            type = OpenSearchClusterManagerPodDisruptionBudget::class,
            name = "OpenSearchClusterManagerPodDisruptionBudget",
            useEventSourceWithName = PDB_EVENT_SOURCE,
            dependsOn = arrayOf("OpenSearchNodeDeployment"),
        ),
      ...
    ],
)
class OpenSearchReconciler(
    private val client: KubernetesApiService,
    private val openSearchClientService: OpenSearchClientService,
) :
    Reconciler<OpenSearch>,
    ErrorStatusHandler<OpenSearch>,
    EventSourceInitializer<OpenSearch> {
```

There are too many DRs associated with 'OpenSearchCR'.

The final parents of DRs are `OpenSearchCR`
but look at it in detail, it's as follows.

```
- OpenSearchCR
   - OpenSearch
       - OpenSearchConfigMap
       - OpenSearchService
       - OpenSearchNodeStatefulSet
       - OpenSearchNodeDeployment
   - OpenSearchDashBoards
       - OpenSearchDashboardsDeployment
       - OpenSearchDashboardsService
       - OpenSearchDashboardsConfigMap
   - OpenSearchSecurity
      - OpenSearchSecurityConfigMap
...
```

like go operator sdk
https://github.com/opensearch-project/opensearch-k8s-operator/blob/main/opensearch-operator/controllers/opensearchController.go#L162

The structure that can map N Reconcilers to a single CR seems to have the advantage of distinguishing between functions and DRs.

Of course, event management will be more complicated through multiple threads
I think it's the user's responsibility.

The structure that all DRs need to be mapped to a single CR as it is now
I think it's getting too complicated as we get more and more DRs

**Comment by csviri** [comment]
Was thinking if it would make sense rather create sub-custom resources. Like `OpenSearchDashBoardsCR`, for which there will be a reconcile. Like for `Deployment` there is a `ReplicaSet` created in the background. Of course this is nicer when the CR is reusable, thus can live without this single type of parent. 

Multiple controllers for a resources sometimes happens in K8S, typically with Ingress there is such intention in the background. So it might be reasonable to allow this, but I still can't see what is the problem this solves in your case. Are there performance issues? This seems to be more like grouping the DRs.

**Comment by csviri** [comment]
@metacosm @andreaTP @shawkins what do you think?

**Comment by 10000-ki** [comment]
> Was thinking if it would make sense rather create sub-custom resources. Like OpenSearchDashBoardsCR, for which there will be a reconcile. Like for Deployment there is a ReplicaSet created in the background

yes that's how I want it to be

> but I still can't see what is the problem this solves in your case. Are there performance issues? This seems to be more like grouping the DRs.

There's no performance issue yet
As you said, the purpose is closer to CR grouping

There are so many DRs connected to a single CR
when Single CR change, there are more and more things to pay attention to.
I want to separate interests of DRs

**Comment by csviri** [comment]
> yes that's how I want it to be

That is completely doable now, you just need to create corresponding custom resources.

**Comment by 10000-ki** [comment]
If parent CR is deleted, all sub-resources must be deleted together.
For example, if 'OpenSearchCR' is deleted, 'OpenSearchDashboardCR' should be deleted 


> Was thinking if it would make sense rather create sub-custom resources.

so 
I think hierarchical CR structures are well worth using in complex Custom Resource Operator

**Comment by csviri** [comment]
@10000-ki if not objection will close this issue
