### ISSUE TITLE
How to filter and watch resources

### ISSUE THREAD

**Issue by 10000-ki** [operator-framework/java-operator-sdk#2184]
I am creating Operator at Cluster Level and I need to watch all the namesapce resources.
(SaaS)

but

```kotlin
@ControllerConfiguration(
    labelSelector = "app.kubernetes.io/managed-by=$OPERATOR_LABEL_V1",
```

```kotlin
@KubernetesDependent(
    resourceDiscriminator = OpenSearchConfigMapDiscriminator::class,
    labelSelector = "app.kubernetes.io/managed-by=$OPERATOR_LABEL_V1",
)
```

Despite defining managed resources through label selector

```
2024-01-08 15:32:04.648 [-1774316039-pool-2-thread-4][][] DEBUG io.fabric8.kubernetes.client.informers.impl.cache.Reflector#L264 - Event received MODIFIED ConfigMap resourceVersion v3942225825 for v1/configmaps
2024-01-08 15:32:04.648 [-1774316039-pool-2-thread-2][][] DEBUG io.fabric8.kubernetes.client.informers.impl.cache.Reflector#L264 - Event received MODIFIED ConfigMap resourceVersion v3942225826 for v1/configmaps
```
![스크린샷 2024-01-08 오후 3 38 57](https://github.com/operator-framework/java-operator-sdk/assets/76486121/55f2f61b-6936-4bb9-b516-adf0ae35bdca)

All namespace resource changes are being received 

Is label-based filtering only possible at the application level?

Since we received so many k8s events
OOM may occur while deserializing this.

**Comment by 10000-ki** [comment]
and now we have to enroll evnetsources about `DependentResource`

like this

https://github.com/operator-framework/java-operator-sdk/blob/706ba26d450a39a72cbf0a72c16ef5bd62399df9/sample-operators/webpage/src/main/java/io/javaoperatorsdk/operator/sample/WebPageDependentsWorkflowReconciler.java#L51

I think that's why the operator gets too many k8s events
Wouldn't it be right if we only get an event for `CR` ?

Or is there a main purpose for us to receive events for the dependent resource types individually?

**Comment by 10000-ki** [comment]
sorry :(

```kotlin
inline fun <reified T : HasMetadata> EventSourceContext<*>.informerEventSource() =
    InformerEventSource(
        InformerConfiguration.from(T::class.java, this)
            .withLabelSelector("app.kubernetes.io/managed-by=$OPERATOR_LABEL_V1")
            .build(),
        this,
    )
```

I didn't add a label selector to this part
I thought it would be automatically registered if I added it to the `Reconciler`

**Comment by 10000-ki** [comment]
sorry :(

```kotlin
inline fun <reified T : HasMetadata> EventSourceContext<*>.informerEventSource() =
    InformerEventSource(
        InformerConfiguration.from(T::class.java, this)
            .withLabelSelector("app.kubernetes.io/managed-by=$OPERATOR_LABEL_V1")
            .build(),
        this,
    )
```

I didn't add a label selector to this part
I thought it would be automatically registered if I added it to the `Reconciler`

**Comment by csviri** [comment]
Hi @10000-ki , np :)  so, evrything works now, or there are still issues with the label selector on cluster scoped resoures?

**Comment by 10000-ki** [comment]
> so, everything works now, or there are still issues with the label selector on cluster scoped resoures? can we close the issue?

yes!

thank you for your help
