### ISSUE TITLE
Allow for multiple controllers reconciling same resource type but with different labels

### ISSUE THREAD

**Issue by goldmann** [operator-framework/java-operator-sdk#2228]
## Bug Report

I have a use case where it would be great to have trow (or more) controllers being able to reconcile the same resource type. 

Let's imaging we have a `ConfigMap` and controller X and Y. Depending on the "type" of the `ConfigMap` we would like to have applied different reconciliation workflows.

Having to squeeze it in a single controller would be pretty complicated and unnecessary. Instead we could just mark the `ConfigMap` with a proper label and the use `labelSelector` on the `@ControllerConfiguration` annotation so that the resource is picked up by correct controller.

Currently it doesn't work:

```
Caused by: io.javaoperatorsdk.operator.OperatorException: Cannot register controller 'generationrequestreconciler': another controller named 'operationgenerationrequestreconciler' is already registered for resource 'configmaps/v1'
```

#### Environment

qosdk 6.6.0, quarkus: 3.7.0, josdk: 4.7.0

JDK 17

**Comment by csviri** [comment]
As discussed this is a know limitation for now (not really a bug :) ), but will implement it since this is a valid use case.
