### ISSUE TITLE
how can i filter events of CR, DR? 

### ISSUE THREAD

**Issue by 10000-ki** [operator-framework/java-operator-sdk#2242]
```kotlin
@ControllerConfiguration(
    labelSelector = "app.kubernetes.io/managed-by=$OPERATOR_LABEL_V1",
    dependents = [
        Dependent(type = OpenSearchCertificatesSecret::class, name = "OpenSearchCertificatesSecret", useEventSourceWithName = SECRET_EVENT_SOURCE),
        Dependent(type = OpenSearchConfigMap::class, name = "OpenSearchConfigMap", useEventSourceWithName = CONFIGMAP_EVENT_SOURCE),
        Dependent(type = OpenSearchSecurityConfigMap::class, name = "OpenSearchSecurityConfigMap", useEventSourceWithName = CONFIGMAP_EVENT_SOURCE),
        Dependent(type = OpenSearchService::class, name = "OpenSearchService", useEventSourceWithName = SERVICE_EVENT_SOURCE),
        Dependent(type = OpenSearchDiscoveryService::class, name = "OpenSearchDiscoveryService", useEventSourceWithName = SERVICE_EVENT_SOURCE),
        Dependent(type = OpenSearchNodeStatefulSet::class, name = "OpenSearchNodeStatefulSet", useEventSourceWithName = STS_EVENT_SOURCE),
        Dependent(type = OpenSearchNodeDeployment::class, name = "OpenSearchNodeDeployment", useEventSourceWithName = DEPLOYMENT_EVENT_SOURCE),
        // @formatter:off
        Dependent(type = OpenSearchDashboardsConfigMap::class, name = "OpenSearchDashboardsConfigMap", useEventSourceWithName = CONFIGMAP_EVENT_SOURCE), // ktlint-disable
        Dependent(type = OpenSearchDashboardsService::class, name = "OpenSearchDashboardsService", useEventSourceWithName = SERVICE_EVENT_SOURCE), // ktlint-disable
        Dependent(type = OpenSearchDashboardsDeployment::class, name = "OpenSearchDashboardsDeployment", useEventSourceWithName = DEPLOYMENT_EVENT_SOURCE), // ktlint-disable
        Dependent(type = OpenSearchClusterManagerPodDisruptionBudget::class, name = "OpenSearchClusterManagerPodDisruptionBudget", useEventSourceWithName = PDB_EVENT_SOURCE), // ktlint-disable
        // @formatter:on
    ],
)
class OpenSearchReconciler
```

```kotlin
Operator(overrider).apply {
            register(OpenSearchReconciler(kubernetesApiService, openSearchClientService, osfarmStorageService)) { config ->
                config.withRetry(
                    GenericRetry().apply {
                        initialInterval = 2000 // default 2000
                        maxAttempts = 10
                    },
                )
                config.withGenericFilter { !it.isTestCR() }
            }
```

I don't want to receive an event for some CRs, so I want to apply filtering
so i used `GenericFilter`

I did it like this, but it didn't work well

![스크린샷 2024-02-16 오후 4 24 57](https://github.com/operator-framework/java-operator-sdk/assets/76486121/9966bc70-e3bc-405d-8a25-3906c8c97f8a)

Is this wrong in the setting?

**Comment by 10000-ki** [comment]
reconcile loop continues to be called even though there's a filter

**Comment by csviri** [comment]
@10000-ki will check deeper, but just make it clear, the generic filter in you sample adds filter for custom resources, what should work. By default it meant to be added though the `@ControllerConfiguration` annotation:

https://github.com/operator-framework/java-operator-sdk/blob/69711cf346d75331a61616bcfe2fd7015c93434b/operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/reconciler/ControllerConfiguration.java#L99-L99

However in debug pic I see informer configuration for a resource class `Service`, which does not seems to be the controller class.

**Comment by 10000-ki** [comment]
![스크린샷 2024-02-16 오후 6 18 14](https://github.com/operator-framework/java-operator-sdk/assets/76486121/17c487fd-777b-49a4-bce3-62e794fb2082)

Even after adding settings to the `@ControllerConfiguration`, `genericFilter` does not seem to pass toward `InformerEventSource`

**Comment by 10000-ki** [comment]
Do all DRs have to register `genericFilter`?

I thought they were sharing the filter applied to the primary

**Comment by 10000-ki** [comment]
Here's the situation.
The operator is already up in a particular Kubernetes cluster

and LocallyRunOperator runs for e2e test

At this time, two operators exist temporarily
so I was looking at the filtering function so that two operators do not affect each other

**Comment by csviri** [comment]
> Here's the situation. The operator is already up in a particular Kubernetes cluster
> 
> and LocallyRunOperator runs for e2e test (with same k8s cluster)
> 
> At this time, two operators exist temporarily so I was looking at the filtering function so that two operators do not affect each other

The easiest is just use different cluster I guess.  But I would also consider label selectors / labels on primary resource.

**Comment by 10000-ki** [comment]
> The easiest is just use different cluster I guess.

yes right but we shared one because the cost of operating multiple k8s clusters in the development environment was high

> But I would also consider label selectors / labels on primary resource

It would be very useful if we could filter with the label applied to the primary resource

**Comment by csviri** [comment]
> It would be very useful if we could filter with the label applied to the primary resource

There is an option for label selector:
https://github.com/operator-framework/java-operator-sdk/blob/69711cf346d75331a61616bcfe2fd7015c93434b/operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/reconciler/ControllerConfiguration.java#L65-L65

**Comment by 10000-ki** [comment]
i found that why `InformerEventSource` didn't have genericFilter

```kotlin
inline fun <reified T : HasMetadata> EventSourceContext<*>.informerEventSource() =
    InformerEventSource(
        InformerConfiguration.from(T::class.java, this)
            .withLabelSelector("app.kubernetes.io/managed-by=$OPERATOR_LABEL_V1")
            .withGenericFilter(ReconcilerFilter())
            .build(),
        this,
    )
```

we must add the settings when registering the InformerEventSource

**Comment by 10000-ki** [comment]
> You can do it now. Note that the all the secondary will be in the cache since those won't have label selectors by default, but won't trigger the reconciliation of the primary, since those primaries won't be in the cache which don't have the label.

and

The filtering method through labelSelector also seems to work.

```
@ControllerConfiguration(
    labelSelector = "app.kubernetes.io/managed-by=$OPERATOR_LABEL_V1"
)
```

so i will use this way thank you :)

**Comment by 10000-ki** [comment]
Even if the primary is filtered with the label, the secondary is automatically filtered, right?

**Comment by csviri** [comment]
> Even if the primary is filtered with the label, the secondary is automatically filtered, right?

not exactly. The other primaries which does not have the labels will not be triggered for this reconciler, but the secondaries won't automatically filtered, will be in the cache, just won't trigger the reconciliation. For testing purposes this might be ok, but of course the state of the caches is not optimal.

**Comment by 10000-ki** [comment]
> not exactly. The other primaries which does not have the labels will not be triggered for this reconciler, but the secondaries won't automatically filtered, will be in the cache, just won't trigger the reconciliation. For testing purposes this is usually ok, but of course the state of the caches is not optimal.

Thank you for your detailed explanation.
I'll keep in mind the above information

@csviri 
Thank you for your assistance.
I am a big fan of `josdk` and I am always grateful to you
