### ISSUE TITLE
409 conflict error

### ISSUE THREAD

**Issue by 10000-ki** [operator-framework/java-operator-sdk#2251]
## ENV

- k8s version : 1.23
- java operator sdk version : 4.4.0

## ERROR Message

```
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: PATCH at: https://ai1.io.navercorp.com:6443/apis/apps/v1/namespaces/opensearchoperatorsecuritye2e-enablesecuritytest-4976a0a5-b09a/deployments/os-test-opensearch-cluster-dashboards?fieldManager=e2etestopensearchreconciler&force=true. Message: Operation cannot be fulfilled on deployments.apps "os-test-opensearch-cluster-dashboards": the object has been modified; please apply your changes to the latest version and try again. Received status: Status(apiVersion=v1, code=409, details=StatusDetails(causes=[], group=apps, kind=deployments, name=os-test-opensearch-cluster-dashboards, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=Operation cannot be fulfilled on deployments.apps "os-test-opensearch-cluster-dashboards": the object has been modified; please apply your changes to the latest version and try again, metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=Conflict, status=Failure, additionalProperties={}).
```

there was an issue that the resource version continued to be upgraded even though there was no spec modification in the deployment
Because of this, infinite reconcile loop execution occurred, which resulted in 409 errors..

**Comment by csviri** [comment]
@10000-ki could you tell more context? Are you using dependent resources, maybe would be great to have a small reproducer if it hard to describe when it exactly happens.

Note that resource version changes even on status and metadata change not just spec.

**Comment by csviri** [comment]
I see this is related to deployments, see also this: https://github.com/operator-framework/java-operator-sdk/issues/2249
But by default should not cause issue. You can verify if you problem is related by setting this feature flag to false:
https://github.com/operator-framework/java-operator-sdk/blob/4e4261293d54f0fed2861b379417c054d8c3c658/operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/ConfigurationService.java#L375-L375

**Comment by csviri** [comment]
Sorry, now I see that you are using v4.4.0 where this was not present yet. (see https://javaoperatorsdk.io/docs/v4-5-migration )

**Comment by 10000-ki** [comment]
is it related to this issue?
https://github.com/kubernetes/kubernetes/issues/95460

**Comment by csviri** [comment]
Yes it seems to be that is an issue on that k8s version you are using from this issue.

**Comment by 10000-ki** [comment]
okay i will upgrade lib version

**Comment by 10000-ki** [comment]
@csviri hi can i ask something??

i saw this pr
https://github.com/operator-framework/java-operator-sdk/pull/2008/files

If the resource version is different, it is impossible to update, so I think the SSA method is adjusting the resource version between actual and target

May I know why you deleted it here?

**Comment by csviri** [comment]
The reason is that there should not be a need for optimistic locking for SSA, since that already handles the ownership of the fields. It is assumed that the desired won't have a resource version set, so there is no optimistic locking happening in this case.

**Comment by shawkins** [comment]
I think it was also a consequence of the annotation based tracking of updates as well as it doesn't need to be locked for correctness.

**Comment by csviri** [comment]
> I think it was also a consequence of the annotation based tracking of updates as well as it doesn't need to be locked for correctness.

At the end it was not needed with event recorder either I think (just was much easier to reason about, also it was before a non-ssa based update, so that is more reasonable there too)

**Comment by 10000-ki** [comment]
if I can't upgrade k8s version to the next 1.23 version (internal problem), are there any other ways??

**Comment by csviri** [comment]
@10000-ki  yes, please try that

**Comment by 10000-ki** [comment]
thank you for guid I'll close this issue
