### ISSUE TITLE
Improve `WorkflowBuilder` API

### ISSUE THREAD

**Issue by metacosm** [operator-framework/java-operator-sdk#2284]
We should have an intermediate API to configure nodes in the workflow in a type-safe and less confusing way. Right now, things are implicitly done, relying on the order of method calls. While what is going on can easily be figured out by looking at the builder's implementation, we should make things type-safe and error-proof via the API.

**Comment by csviri** [comment]
see also: https://github.com/operator-framework/java-operator-sdk/issues/2256#issuecomment-1989688502
