### ISSUE TITLE
Handling Cluster Scoped Primary Resource in Dependent Resource `SecondaryToPrimaryMapper`  

### ISSUE THREAD

**Issue by csviri** [operator-framework/java-operator-sdk#2311]
Currently by default Dependent Resource assumes that the primary resource is namespace scoped, see:

https://github.com/operator-framework/java-operator-sdk/blob/0b17878ca5497d97838faa0bb8754ca61b8bd414/operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/KubernetesDependentResource.java#L90-L90

This is something users have to then handle explicitly, by overriding the `SecondaryToPrimaryMapper`, see:

https://github.com/operator-framework/java-operator-sdk/issues/2310#issuecomment-2017523701

In DRs we don't have access to the class of primary to check if it is namespace scoped. But we might create some workarounds, like passing it as a flag for managed resources automatically.

**Comment by metacosm** [comment]
Closed by #2321
