### ISSUE TITLE
Remove automated observed generation handling?

### ISSUE THREAD

**Issue by csviri** [operator-framework/java-operator-sdk#2329]
With SSA handling this required `UpdateControl.patchStatus` or `UpdateControl.patchResourceAndStatus` to be called. Which is much less transparent now.

This feature is also not that useful / can be done easily manually. Also without it `ReconcilierDispatcher` implementation will be simpler.

**Comment by metacosm** [comment]
How would things be handled without it?

**Comment by csviri** [comment]
User would  just set it in the reconciler.
