### ISSUE TITLE
If the condition is not satisfied, the DR will be deleted and will not be regenerated.

### ISSUE THREAD

**Issue by 10000-ki** [operator-framework/java-operator-sdk#2343]
![스크린샷 2024-04-12 오후 2 00 28](https://github.com/operator-framework/java-operator-sdk/assets/76486121/c5149c75-cc4f-4bca-aa4c-02cc05f8a3d5)
![스크린샷 2024-04-12 오후 2 00 36](https://github.com/operator-framework/java-operator-sdk/assets/76486121/a741bf35-a98f-4768-8a27-c092a569af45)

If condition is not satisfied, dr seems to be deleted.

The first one or two failures may occur, but conditions may succeed after several retries

Is there a way to re-create `DR` ??

Or am I not using conditions well?

**Comment by csviri** [comment]
@10000-ki If the condition is met again, the resource is reconciled again, thus recreated.

**Comment by 10000-ki** [comment]
> If the condition is met again, the resource is reconciled again, thus recreated.

![스크린샷 2024-04-12 오후 4 07 29](https://github.com/operator-framework/java-operator-sdk/assets/76486121/33f9fec0-d72c-4740-9d9e-44c44c591216)

@csviri oh sorry

Only for `activationCondition`
It's being filtered by markedForDelete
There was some confusion, Thank you for explanation
