### ISSUE TITLE
`CRUDKubernetesDependentResource#delete()` Deletes Non-Children Resources

### ISSUE THREAD

**Issue by coltmcnealy-lh** [operator-framework/java-operator-sdk#2349]
## Bug Report

I have a `KafkaUserDR` which is a `CRUDKubernetesDependentResource<KafkaUser, LHCluster>`. In my `LHClusterReconciler#reconcile` method, I call `kafkaUserDR.delete(...)`.

`KafkaUser` is the class of the CRD that is created by the Dependent Resource, and `LHCluster` is the primary.

The name of the Primary resource (the `LHCluster`) is `my-cluster`. I had another CRD of a different type (`LHKafkaUser`), and that an instance of that CRD also named `my-cluster`.

The `LHKafkaUser` CRD creates as a dependent a `KafkaUser` and therefore put an `ownerRef` on the created `KafkaUser`. The ownerRef on that `KafkaUser` correctly reported the `kind: LHKafkaUser`.

However, in the LHCluster Reconciler, calling `delete()` on the `kafkaUserDR` incorrectly deleted that resource: it was owned by the `LHKafkaUser` and NOT by the `LHCluster`.

#### Potential Fix

I think the fix is that the `CRUDKubernetesDependentResource#delete()` method needs to check both the `name` _and_ `kind` on the `ownerRef` of resources before deleting it. Right now, the behavior suggests that it is not checking the `kind`.

#### Environment

Using a KIND cluster. JOSDK version `4.4.x`

**Comment by coltmcnealy-lh** [comment]
One workaround for now is to just make sure to avoid naming clashes. But that's not exactly ideal, and when we ship our Operator as a product to our customers (which we are doing soon), we can't guarantee that they will follow such practices.

**Comment by csviri** [comment]
Hi @coltmcnealy-lh , could you create a minimal reproducer pls, it is probably not the case with the Kind-s, since the Kind checked: https://github.com/operator-framework/java-operator-sdk/blob/6daf2dc828c8a27a94fe26adc72a4f6518e74eaa/operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/AbstractDependentResource.java#L92-L92

Thourght the statically typed API.

**Comment by coltmcnealy-lh** [comment]
Thanks for the update! Is there a ticket I can use to track the V5 progress?

Also, for now it looks like I can solve the issue by implementing `SecondaryToPrimaryMapper` in my Dependent Resources. Is that correct?

**Comment by csviri** [comment]
> Is there a ticket I can use to track the V5 progress?

There is a milestone:
https://github.com/operator-framework/java-operator-sdk/milestone/5

> Also, for now it looks like I can solve the issue by implementing SecondaryToPrimaryMapper in my Dependent Resources. Is that correct?

yes, definitely, you can do that, that will fix it.
