### ISSUE TITLE
What is the correct way to start an operator using own custom KubernetesClient instance?

### ISSUE THREAD

**Issue by unclechu** [operator-framework/java-operator-sdk#2432]
I’m creating own `KubernetesClient` instance for the tests, configuring it to point to a [K3S](https://java.testcontainers.org/modules/k3s/) (see `org.testcontainers:k3s:1.19.8` package) test environment. Basically constructing `org.testcontainers.k3s.K3sContainer` instance, calling `.start()` method at the beginning and `.stop()` at the end. Creating `KubernetesClient` instance like this (Spring “bean”, the code is in Kotlin):

``` kotlin
  @Bean
  fun kubernetesClient(): KubernetesClient {
    val kubeConfig = Config.fromKubeconfig(KubernetesInitializer.kubeContainer.kubeConfigYaml)
    return KubernetesClientBuilder().withConfig(kubeConfig).build()
  }
```

`.kubeConfigYaml` is generated YAML kubeconfig contents.

Then I start my operator like this (where `kubernetesClient` is that `KubernetesClient` instance):

``` kotlin
      val operator = Operator(kubernetesClient, null)
      operator.register(myOperatorReconcilerInstanceHere)
      operator.start()
```

It works just fine except that this `Operator` constructor variant is marked as _deprecated_:

``` java
   /** @deprecated */
   @Deprecated(
      since = "4.4.0"
   )
   public Operator(KubernetesClient client, Consumer overrider) {
      this(initConfigurationService(client, overrider));
   }
```

And another one is _private_:

``` java
   Operator(KubernetesClient kubernetesClient) {
      this(kubernetesClient, (Consumer)null);
   }
```

What is a correct way of doing this? Or is there other way to supply  `Operator` with custom kubeconfig without creating intermediate files or using command-line arguments/environment variables?

**Comment by unclechu** [comment]
By looking at the `ConfigurationService`-based constructor variant (`public Operator(ConfigurationService configurationService)`) I came up with this (calling `.withKubernetesClient` method):

``` kotlin
val operator = Operator({ it.withKubernetesClient(kubernetesClient) })
```

Is this the answer?

**Comment by csviri** [comment]
> By looking at the `ConfigurationService`-based constructor variant (`public Operator(ConfigurationService configurationService)`) I came up with this (calling `.withKubernetesClient` method):
> 
> ```kotlin
> val operator = Operator({ it.withKubernetesClient(kubernetesClient) })
> ```
> 
> Is this the answer?

Hi, yes, this is it!
