### ISSUE TITLE
Primary InformerEventSource never get called from withPrimaryToSecondaryMapper. 

### ISSUE THREAD

**Issue by Jojoooo1** [operator-framework/java-operator-sdk#2473]
#### What did you do?

I am trying to trigger the deployment of multiple dependent resource (in this case LimitRange) by using `withPrimaryToSecondaryMapper` in the primary `InformerEventSource` but the code never get executed.

Here is the implementation:

```java
@Slf4j
@ControllerConfiguration(
    dependents = {
      @Dependent(name = LimitRangeDependent.COMPONENT, type = LimitRangeDependent.class),
    })
public class NamespaceClassReconciler
    implements Reconciler<MyCRD>, EventSourceInitializer<MyCRD> {

  @Override
  public UpdateControl<MyCRD> reconcile(MyCRDs primary, Context<MyCRD> context) {
    return UpdateControl.updateStatus(primary);
  }

  @Override
  public Map<String, EventSource> prepareEventSources(EventSourceContext<MyCRD> context) {

    var crdES =
        new InformerEventSource<>(
            InformerConfiguration.from(MyCRD.class, context)
                .withPrimaryToSecondaryMapper(
                        primary -> {
                          log.info("THIS IS NEVER CALLED");
                          return Set.of();
                        })
                .build(),
            context);

    return EventSourceInitializer.nameEventSources(crdES);
  }
}
```

#### What did you expect to see?

I expect `withPrimaryToSecondaryMapper` to be executed.

#### Environment

**Kubernetes cluster type:**

Using k3s v1.30.2+k3s1

`$ Mention java-operator-sdk version from pom.xml file`

6.7.1

`$ java -version`

openjdk version "21.0.2" 2024-01-16 LTS
OpenJDK Runtime Environment Temurin-21.0.2+13 (build 21.0.2+13-LTS)
OpenJDK 64-Bit Server VM Temurin-21.0.2+13 (build 21.0.2+13-LTS, mixed mode, sharing)

`$ kubectl version`

Client Version: v1.30.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.2+k3s1

**Comment by csviri** [comment]
Hi @Jojoooo1 what are you probably looking for is the `SecondaryToPrimaryMapper` (not `PrimaryToSecondary`), see details here: https://javaoperatorsdk.io/docs/features/#managing-relation-between-primary-and-secondary-resources

The primaryToSecondary is called when the resource is read, thus `context.getSecondaryResource`.

**Comment by Jojoooo1** [comment]
Hi @csviri thank you for taking the time to answer, I was actually trying to use `withPrimaryToSecondaryMapper` to map a one-to-many relationship between my CRD and multiple Dependent Resource in various namespaces. I thought that was the recommended way of creating this kind of relationship (from one primary to multiple dependent).

**Comment by csviri** [comment]
You still need both in that case:

https://github.com/operator-framework/java-operator-sdk/blob/89ef224964ea1c22190dcc05524d176eecdbdc97/operator-framework/src/test/java/io/javaoperatorsdk/operator/sample/primarytosecondary/JobReconciler.java#L70-L74

**Comment by csviri** [comment]
see also: https://javaoperatorsdk.io/docs/dependent-resources/#read-only-dependent-resources-vs-event-source

I guess it is read only? for you

**Comment by Jojoooo1** [comment]
I was actually trying to do something that was not possible, which was creating dynamically a list of dependent resources using only on dependent definition.

**Comment by csviri** [comment]
that is possible only with standalone mode, here you can see lot's of related magic:
https://github.com/csviri/kubernetes-glue-operator 
:)

**Comment by Jojoooo1** [comment]
Many thanks for all the answers :).
