### ISSUE TITLE
Inquiry about operator gracefulshutdown function

### ISSUE THREAD

**Issue by 10000-ki** [operator-framework/java-operator-sdk#2476]
The current gracefulshutdown support method is as follows.

```java
  public void stop(Duration gracefulShutdownTimeout) throws OperatorException {
    if (!started) {
      return;
    }
    log.info(
        "Operator SDK {} is shutting down...", configurationService.getVersion().getSdkVersion());
    controllerManager.stop();

    configurationService.getExecutorServiceManager().stop(gracefulShutdownTimeout);
    leaderElectionManager.stop();
    if (configurationService.closeClientOnStop()) {
      getKubernetesClient().close();
    }

    started = false;
  }
```

Receiving `timeoutseconds` as a method parameter has several disadvantages.

### 1. Difficult to utilize directly in spring boot

![스크린샷 2024-08-02 오후 1 34 57](https://github.com/user-attachments/assets/77f7713d-681a-4d19-afc8-f38467bd4d50)

Difficult to pass parameters to bean destroy configuration

### 2. Sometimes graceful shutdown is not performed unintentionally

![스크린샷 2024-08-02 오후 1 36 57](https://github.com/user-attachments/assets/a13aae83-cedc-4dff-8612-4100cb703d5b)

There are quite a few places that call the stop method, and I don't know if it was intentional, but in most cases, the terminateseconds setting is ignored.

## Suggestion

```java
  @Override
  public void stop() throws OperatorException {
    int timeoutSeconds = configurationService.getTerminationTimeoutSeconds();
    if (timeoutSeconds > 0) {
      stop(Duration.ofSeconds(timeoutSeconds));
    } else {
      stop(Duration.ZERO);
    }
  }
```

`configurationService.getTerminationTimeoutSeconds`

I know the above setting is no longer supported, but

To solve the two problems above, I think it would be a good idea to continue supporting this setting.

Or any other good ideas?

**Comment by csviri** [comment]
Hi @10000-ki, Thanks. Yes, this makes sense. We should definitely consider this for v5. @metacosm, what do you think?

@10000-ki would it be possible to create a PR for this (targeting `next` branch) ?

**Comment by 10000-ki** [comment]
> would it be possible to create a PR for this (targeting next branch) ?

@csviri 
Sure I can work on it.
I will work on it, create a PR, and request a review.
