### ISSUE TITLE
[Suggestion] Resource Diff Printer

### ISSUE THREAD

**Issue by 10000-ki** [operator-framework/java-operator-sdk#2492]
## Idea

I'd like to propose an idea. 
How about providing a utility function that outputs the diff information to show which fields have changed between the actual resource and the desired resource?

Currently, it seems that such a feature doesn't exist, so when unintended events are generated, we have to log both the actual and desired resources as text and manually compare them field by field to find the differences. This process takes too much time.

## Example

```kotlin
    override fun match(
        actualResource: StatefulSet,
        desired: StatefulSet,
        primary: OpenSearch,
        context: Context<OpenSearch>,
    ): Matcher.Result<StatefulSet> {
        println(ResourceDiffPrinter.printDiff(actualResource, desired))
    }
```

---

```
"""
Diff : 
(actual) -> (desired)
annotations.last-modification-timestamp: "2024-08-13T11:07:04+09:00" -> annotations.last-modification-timestamp: "2024-08-13T12:07:04+09:00" 
spec.replicas: "3" -> spec.replicas: "4"
"""
```

**Comment by csviri** [comment]
Would make sense IMO, I can imagine that as part of `SSABasedGenericKubernetesResourceMatcher`, that could also log this information. 

Do you plan to also create a PR?

**Comment by 10000-ki** [comment]
> Do you plan to also create a PR?

@csviri 
Of course! In that case, would it be okay if I work on it and then submit a PR?

**Comment by 10000-ki** [comment]
@csviri 
the PR should be created based on the `next` branch right??

**Comment by metacosm** [comment]
> @csviri the PR should be created based on the `next` branch right??

Yes, please.

**Comment by 10000-ki** [comment]
done
