### ISSUE TITLE
Read-Only BulkDependentResource

### ISSUE THREAD

**Issue by matteriben** [operator-framework/java-operator-sdk#2506]
## Bug Report

I'd like a version of `BulkDependentResource` which is read-only, similar to `KubernetesDependentResource` which can then optionally implement {`Creator`, `Updater`, `Deleter`}.

It might be convenient for some use case to have `Creator` & `Deleter` "out of the box". The API makes it easy to add `Creator` & `Deleter`, removing them seems less simple.

#### What did you do?

Currently, I'd like to make use of a `BulkDependentResource` which can update, but not create or delete. I'd like to let the JOSDK know my intention by implementing `Updater` only (neither `Creator` nor `Deleter`), but this does not appear to be possible.

#### Environment

**Kubernetes cluster type:**

`$ Mention java-operator-sdk version from pom.xml file`

`$ java -version`

`$ kubectl version`

**Comment by csviri** [comment]
Hi, thx for the issue, this is already implemented for v5. Will close this as duplicate if no objections.

**Comment by matteriben** [comment]
Hi, thanks for the quick response. No objections to closing this.
