### ISSUE TITLE
How do I label an issue as "enhancement"?

### ISSUE THREAD

**Issue by matteriben** [operator-framework/java-operator-sdk#2507]
## Bug Report

How do I label an issue as "enhancement"?

#### What did you do?

I tried to open an issue labeled "enhancement" as described in [CONTRIBUTING](https://github.com/operator-framework/java-operator-sdk/blob/main/CONTRIBUTING.md?plain=1#L31-L36). The only available options were to create a bug or security report, and I am unable to add labels.

#### What did you expect to see?

I expected an option to create an issue as an enhancement or add a label of "enhancement".
https://github.com/operator-framework/java-operator-sdk/issues/new/choose

#### What did you see instead? Under which circumstances?

Only options were bug or security report, no ability to add a label.

#### Environment

https://github.com

#### Possible Solution

- Create an [issue template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests) for enhancements.
- Update the [documentation](https://github.com/operator-framework/java-operator-sdk/blob/main/CONTRIBUTING.md?plain=1#L31-L36)

**Comment by csviri** [comment]
True, that is missing. Thx for raising. 

Although you can always make a blank issue, but feel free also to create a PR for enhancement template :)

**Comment by csviri** [comment]
Thank you, pr merged, if no objections, will close this issue.
