### ISSUE TITLE
Could you let me know the release date for v5?

### ISSUE THREAD

**Issue by 10000-ki** [operator-framework/java-operator-sdk#2545]
Could you let me know the release date for v5 (next branch)?

I am preparing a technical sharing seminar on JOSDK within our company, and I think it would be better to explain it based on v5 after its release. Could you let me know the release schedule for v5?

**Comment by csviri** [comment]
From our side the v5 is almost ready, there might be some additional PR-s mainly regarding release notes and some minor improvements until the release. However the intention is to make the release based on fabric8 client v7, so basically we are waiting for that, that is also close to release but we don't have any exact target date for that, hopefully until end of this Month or maybe next it should be released.

**Comment by 10000-ki** [comment]
thank you for letting me know!

**Comment by metacosm** [comment]
Closing this issue since it's been addressed.
