### ISSUE TITLE
Typo in method name: ConfigurationServiceOverrider#wihtParseResourceVersions()

### ISSUE THREAD

**Issue by tombentley** [operator-framework/java-operator-sdk#2560]
#### What did you do?

Use the `withConfigurationService` method of `LocallyRunOperatorExtension`

#### What did you expect to see?

Methods spelled correctly.

#### What did you see instead? Under which circumstances?

A method called `wihtParseResourceVersions` on the type `ConfigurationServiceOverrider`.

#### Environment

N/A

**Comment by csviri** [comment]
Hi @tombentley , thx, (this is already fixed for v5, feel free to create a PR for current version in case. )
